export const ENGLocalizedStrings = {
  Public: {
    All: "All",
    Confirm: "Confirm",
    Cancel: "Cancel",
    Back: "Back",
    Save: "Save",
    Close: "Close",
    Language: "Language: English",
    Post: "Post",
    Friend: "Friends",
    Username: "Username",
    About: "About",
    Today: "Today, what do you want to do?",
    Detail: "Detail",
    EditProfile: "Edit Profile",
    ChangePassword: "Change Password",
    LogOut: "Log Out",
    SetingProfile: "Setting Profile",
    Mail: "Email",
    Phone: "Phone Number",
    Birthday: "Birth Date",
    Active: "Created Date",
    FriendFind: "Find Friend",
    FriendView: "View All Friend",
    Conform: "Confirm",
    LogoutConfirm: "Are you sure you want to log out?",
    More: "More",
    AddFriend: "Add Friend",
    UnFriend: "Unfriend",
    CancelFriendRequest: "Cancel request",
    RefuseFriendRequest: "Refuse",
    AcceptFriendRequest: "Accept",
    ReportFriend: "Report",
    Block: "Block",
    Vietnamese: "Vietnamese",
    English: "English",
    ErrorFetchingProfile: "Error fetching profile!",
    Biography: "Biography",
    UnknownUser: "YourVibes user",
    Public: "Public",
    Everyone: "Everyone",
    Private: "Only me",
    MinuteAgo: "minutes ago",
    HourAgo: "hours ago",
    DayAgo: "days ago",
    Action: "Action",
    CommonActions: "Click your comment ...",
    Comment: "Comments",
    Reply: "Reply",
    ReportComment: "Report Comment",
    Day: "Day",
    HideInfo: "has hidden personal information",
    FriendOnly: "only friends can see",
    UserLikePost: " List of users liked post",
    NoUserLikePost: "No one liked this post",
    ReplyClick: "Click and write your Reply here...",
    CommentClick: "Click and write your Comment here...",
    LoginLoading: "Loading Login ...",
    Home: "Home",
    Settings: "Settings",
    Profile: "Profile",
    LoginStatus: "Please log in again",
    Messages: "Messages",
    LoadMore: "Load more",
    Search: "Search",
    Error: "Error",
    Yes: "Yes",
    No: "No",
    Delete: "Delete",
    GenericError: "An error occurred, please try again later!",
    Message: "Message",
    Trending: "Trending",
    People: "People",
    Discover: "Discover People",
    Connect: "Connect with new friends and expand your network",
    UserNotFound: "User not found",
    ShowOnlyUnrequested: "Show only unrequested friends",
    SearchUsers: "Search users...",
    ErrorLoading: "Error loading data!",
    FriendRequests: "Friend Requests",
    NoFriendRequests: "No friend requests",
    Accept: "Accept",
    Decline: "Decline",
    AllUsers: "Expand your network",
    Feed: "Feed",
    Birtday: "Friends birthday reminder!",
    Dayof: "Birthday:",
    YearsOld: "years old",
    NoBirthdays: "No birthdays today",
    ConfirmLogoutMessage: "Are you sure you want to log out?",
    ConfirmLogout: "Confirm Logout",
    Logout: "Logout",
  },

  Suggested: {
    SuggestedFriends: "Suggested Friends",
    Hide: "Hide",
    SeeMore: "See more",
    Why: "Why do I see these friends?",
    Dont: "I don't want to see these friends",
    FriendRequestSent: "Waiting...",
    AddFriend: "Add friend",
    WhyExplanation: "These suggestions are based on factors such as:",
    WhyFactor1: "Mutual friends",
    WhyFactor2: "Similar interests",
    WhyFactor3: "Recent activity on social media",
    WhyConclusion:
      "We use an algorithm to find people you might know or want to connect with!",
      NoMoreSuggestions: "No more suggestions!",
  },

  Form: {
    Label: {
      Email: "Email",
      Password: "Password",
      FamilyName: "Family Name",
      Name: "Name",
      Phone: "Phone Number",
      BirthDay: "Birth Date",
      GetOTP: "Enter OTP",
      OTP: "OTP Code",
      ConfirmPassword: "Confirm Password",
      Biography: "Biography",
    },
    RequiredMessages: {
      FamilyNameRequiredMessage: "Please enter family name!",
      NameRequiredMessage: "Please enter name!",
      PhoneRequiredMessage: "Please enter phone number!",
      BirthDayRequiredMessage: "Please select a birth date!",
      EmailRequiredMessage: "Please enter email!",
      PasswordRequiredMessage: "Please enter password!",
      ConfirmPasswordRequiredMessage: "Please confirm your password!",
      AgreeRequiredMessage: "Please agree to the terms!",
      OTPRequiredMessage: "Please enter OTP code!",
      OTPPressRequiredMessage: "Please receive OTP code!",
      BirthDayInvalidMessage: "Invalid birth date!",
      PhoneInvalidMessage: "Invalid phone number!",
      InvalidEmailMessage: "Invalid email!",
      PasswordMinLengthMessage: "Password must be at least 8 characters long!",
    },
    TypeMessage: {
      EmailTypeMessage: "Invalid email!",
      PasswordTypeMessage: "Password must be over 8 characters!",
      ConfirmPasswordTypeMessage: "Confirm password is invalid!",
      OTPTypeMessage: "OTP code must be a 6-digit string!",
      PhoneTypeMessage: "Phone number must be a 10-digit string!",
      PleaseOldPasswordDifferentNewPassword:
        "New password must be different from old password!",
      PleaseInformationDifferent: "Please enter all information",
    },
  },
  Login: {
    LoginButton: "Login",
    ForgotPasswordText: "Forgot password?",
    DontHaveAccout: "Don't have an account?",
    SignUpNow: "Sign up now!",
    Or: "Or",
    LoginFailed: "Email or password is wrong!",
    AccountLocked: "Your account is locked!",
    changeLanguage: "Change Language: Vietnamese",
    InvalidInput: "Invalid input!",
    LoginSuccess: "Login successful!",
  },
  SignUp: {
    SignUpButton: "Sign up",
    SignUpSuccess: "Sign up successful! Please log in again",
    SignUpFailed: "Sign up failed!",
    OTPSuccess: "OTP has been sent successfully!",
    OTPAlreadySent: "OTP has been sent and is valid for 10 minutes!",
    OTPFailed: "Sending OTP failed!",
    OTPExpired: "OTP does not exist or has expired!",
    OTPFailedUserHasRegistered: "The account already exists!",
    OTPEmail: "OTP has been sent to your email",
    AlreadyHaveAccount: "Already have an account?",
    LoginNow: "Log in now!",
    AgreePolicies: "I agree to the YourVibes terms",
  },
  AddPost: {
    NewPost: "New post",
    WhatDoYouThink: "What do you think?",
    PrivacyText: "Share your post with",
    PostNow: "Post now",
    CreatePostSuccess: "Create post successful!",
    CreatePostFailed: "Create post failed!",
    EmptyContent: "Missing content or media file",
    PickImgFailed: "Pick images failed!",
    UploadImage: "Upload Image",
    CensorPost: "Your post is under review, please wait.",
  },
  ObjectPostPrivacy: {
    PublicDescription: "Everyone on YourVibes",
    FriendDescription: "Only friends on YourVibes",
    PrivateDescription: "Only you can see the post",
    PostPrivacy: "Post's privacy",
    Contents: {
      WhoCanSee: "Who can see your post?",
      CanFind: "Your post may appear on your profile and in search results.",
      DefaultPrivacy1: "Although the default audience is ",
      DefaultPrivacy2: ", you can change the audience for this specific post.",
    },
    ChoosePrivacy: "Choose Privacy",
  },
  ObjectProfile: {
    ProfilePrivacy: "Profile's privacy",
    Contents: {
      WhoCanSee: "Who can see your information?",
      DefaultPrivacy2:
        ", but you can change the privacy for your account details.",
    },
  },
  Post: {
    EditPost: "Edit post",
    EditPrivacy: "Edit post's privacy",
    DeletePost: "Delete post",
    Advertisement: "Advertisement",
    ReportPost: "Report post",
    LikePostFailed: "Like post failed!",
    SharePostSuccess: "Share post successful!",
    SharePostFailed: "Share post failed!",
    SharePost: "Share",
    DeleteNewFeed: "Delete (hide) new feed",
    NoContent: "Content is empty",
    Sponsor: "Sponsored",
    NoPosts: "No posts found",
    ShareContent: "Enter the content you want to share...",
    CharacterLimit: "10000 characters",
    CharacterLimitR: "255 characters",
    NoTrendingPosts: "No trending posts found",
  },
  PostDetails: {
    ViewReplies: "View replies",
    HideReplies: "Hide replies",
    Save: "Save",
    Cancel: "Cancel",
    Error: "Error",
    ErrorReplies: "Failed to get replies!",
    ReportComment: "Report comment",
    EditComment: "Edit comment",
    DeleteComment: "Delete comment",
    DeleteCommentSusesfully: "Delete comment successful!",
    DeleteCommentFailed: "Delete comment failed!",
    ActionOptions: "Action options",
    ReportSusesfully: "Reported succeeded!",
    Success: "Success",
    EditCommentSuccess: "Edit comment successful!",
    EditCommentFailed: "Edit comment failed!",
    EditReplySuccess: "Edit reply successful!",
    EditReplyFailed: "Edit reply failed!",
    DeteleReplyFailed: "Delete reply failed!",
    DeteleReplySuccess: "Delete reply successful!",
    CommentSuccess: "Comment successful!",
    CommentFailed: "Comment failed!",
    ReplySuccess: "Reply successful!",
    ReplyFailed: "Reply failed!",
    Yes: "Yes",
    No: "No",
    CommentNotFound: "Comment not found!",
    CommentLimit: "500 characters",
  },
  Profile: {
    Posts: {
      GetPostsFailed: "Failed to get posts!",
      GetOnePostFailed: "Failed to get post!",
    },
    Info: {
      GetInfoFailed: "Failed to get user's infomation!",
    },
    Friend: {
      SendYouARequest: "Sent you a friend request!",
      SendARequest: "Sent friend request!",
      SendRequestFailed: "Failed to send friend request!",
      SendRequestSuccess: "Friend request sent successfully!",
      FriendResponseFailed: "Failed to respond to friend request!",
      FriendResponseSuccess: "Friend request response successful!",
      CancelRequestFailed: "Failed to cancel friend request!",
      CancelRequestSuccess: "Friend request canceled successfully!",
      UnfriendFailed: "Failed to unfriend!",
      UnfriendSuccess: "Unfriend successful!",
      UnfriendConfirm: "Are you sure you want to unfriend this user?",
    },
  },
  UpdatePost: {
    UpdatePostSuccess: "Update post successful!",
    UpdatePostFailed: "Update post failed!",
  },
  DeletePost: {
    DeleteConfirm: "Are you sure you want to delete this post?",
    DeleteSuccess: "Delete post successful!",
    DeleteFailed: "Delete post failed!",
  },
  UpdateProfile: {
    UpdateProfile: "Update profile",
    UpdateFailed: "Update profile failed!",
    UpdateSuccess: "Update profile successful!",
  },
  Search: {
    Search: "Search",
    SearchPlaceholder: "Searching...",
    SearchFailed: "Search failed!",
    NoUsers: "No user found",
    TrySearch: "Try searching some keyword",
  },
  Notification: {
    Notification: "Notifications",
    NoNotification: "No notification",
    Items: {
      LikePost: "liked your post: ",
      SharePost: "shared your post: ",
      CommentPost: "commented on your post: ",
      Friend: "sent you a friend request.",
      AcceptFriend: "accepted your friend request.",
      NewPost: "posted a new post.",
      LikeComment: "liked your comment: ",
      NewPostPersonal: "Your post has been successfully published:",
      NewPostError: "Your post encountered an error",
      BlockCreatePost: "Your post has been blocked",
      nsfw: "due to containing sensitive content",
      political: "due to containing inappropriate political content",
      violence: "due to containing violent content",
      DeactivatePostContent:
        "Your post has been blocked for violating our terms and conditions. If you believe this is a mistake, please contact our support team for review.",
      ActivacePostContent:
        "Your post has been reactivated after review. Thank you for your patience.",
      DeactivateCommentContent:
        "Your comment has been blocked for violating our terms and conditions. If you believe this is a mistake, please contact our support team for review.",
      ActivaceCommentContent:
        "Your comment has been reactivated after review. Thank you for your patience.",
    },
  },
  ListFriends: {
    ListFriends: "List friends",
    Search: "Search . . .",
    ViewProfile: "View profile",
    Unfriend: "Unfriend ",
    Block: "Block ",
    Cancel: "Cancel",
  },

  Ads: {
    Ads: "Post Advertisement",
    TimeAndBudget: "Duration and Budget",
    Minimum: "- Minimum: {{price}}/day (Max date: 30 days)",
    DaysAds: "Number of advertisement days:",
    TimeAds: "Advertisement duration: ",
    StartDate: "Start Date",
    EndDate: "End Date",
    BudgetAds: "Budget: ",
    PaymentMethod: "Payment method",
    AdvertisePostFailed: "Advertise post failed!",
    AdvertisePostSuccess: "Advertise post successful!",
    ActiveCampaign: "Active campaign",
    HideCampaign: "Hide campaign",
    ShowCampaign: "Show campaign",
    Campaign: "Campaign",
    End: "End",
    RemainingTime: "Remaining time",
    Day: "Day",
    Grant: "Grant",
    Status: "Status",
    PaymentSuccess: "Payment successful.",
    PaymentFailed: "Payment failed.",
    NoCampaign: "No campaign found",
    AdvertisePostPending:
      "Advertisement is pending, please check the process again.",
    CampaignStatus: "Campaign status",
    Click: "Total clicks",
    TotalReach: "Total reach",
    TotalImpressions: "Total impressions",
    AdsManagement: "Ads Management",
    SelectAds: "Select article to advertise",
    NoAdsFound: "No ads found",
    SearchAds: "Search . . .",
    ExportAds: "Export Ads",
    StartDay: "Start day",
    EndDay: "End day",
    ViewDetails: "View details",
    Voucher: "Voucher",
    VoucherApplied: "Voucher applied",
    InvalidVoucher: "Invalid voucher",
    StatusActive: "Status Active Campaign",
    Pending: "Pending",
    Active: "Active",
    Done: "Done",
    Completed: "Completed",
    ErrorFetchingStatistics: "Error fetching statistics!",
    ViewHistory: "View history",
    NoHistoryFound: "No history found",
    NoAdsHistory: "No ads history",
    HistoryforPost: "History for post",
    Discount: "Discount",
    LimitDay:
      "- 30-day limit because the MOMO payment method does not support payments beyond 30 days!",
  },

  Report: {
    ReportPost: "Why are you reporting this post?",
    ReportUser: "Why are you reporting this user?",
    ReportComment: "Why are you reporting this comment?",
    ReportSuccess: "Reported successfully!",
    ReportFailed: "Report failed!",
    ReportUserFailed: "Report failed, you have already reported this account!",
    ReportPostFailed: "Report failed, you have already reported this post!",
    ReportCommentFailed:
      "Report failed, you have already reported this comment!",
    Note: "If you see a threat or someone in danger, don't hesitate to seek help and report to local emergency services before reporting to YourVibes.",
    placeholder: "Write your report here...",
    Report: "Report",
    ReportAlreadyExists: "Report already exists",
  },
  ChangePassword: {
    ChangePassword: "Change password",
    ChangePasswordFailed:
      "Password change failed, please check the password again",
    ChangePasswordSuccess: "Password change successful!",
    OldPassword: "Old password",
    NewPassword: "New password",
    ConformPassword: "Confirm password",
    Email: "Email",
    SendOTP: "Send OTP",
    OTP: "OTP",
    ConformChangePassword: "Confirm change password",
  },

  Messages: {
    SearchUser: "Please enter name who you want to contact",
    FriendBar: "Friends",
    CreateChatGroup: "Create chat group",
    ChooseFriendToChat: "Choose conversation to chat",
    ChooseFriendToConnect: "Choose conversation to connect",
    NoMessages: "No messages",
    EnterMessage: "Enter the message",
    FindFriendInModal: "Find your friends",
    Cancel: "Cancel",
    Confirm: "Confirm",
    UserProfile: "User Profile",
    ProfilePage: "Profile Page",
    Block: "Block",
    Reply: "Reply",
    ScrollToBottom: "Scroll to bottom",
    Connecting: "Connecting",
    Connected: "Connected",
    You: "You",
    MessageTooLong: "Message must not exceed 500 characters",
    GroupMinimumMembers: "Group chat must at least 3 members",
    GroupCreationFailed: "Create Chat Group Failed",
    UserNotLoggedIn: "Please Login",
    GroupSelectionInfo: "Choose at least 2 FRIENDS to create chat group",
    SelectedFriends: "Selected",
    MinimumFriends: "Minimum",
    Error: "Error",
    OK: "OK",
    Friends: "Friends",
    NoConversations: "No any Conversation exists",
    FriendsTab: "Friends",
    AllContactsTab: "All Contacts",
    Conversations: "Conversations",
    SelectedMembers: "Selected Members",
    StartConversation: "Start Conversation",
    SelectConversation: "Select Conversation",
    SelectConversationToChat: "Select Conversation To Chat",
    TypeMessage: "Type a message",
    ErrorFetchingConversations: "Error fetching conversation",
    ConfirmDeleteMessage: "Confirm delete this message ?",
    ConfirmDeleteConversation: "Confirm delete this conversation ?",
    ConversationDeleted: "Conversation was deleted successfully!",
    DeleteConversation: "Delete Conversation",
    LeaveConversation: "Leave Conversation",
    ErrorFetchingFriends: "Error fetching friends",
    OnlyImageFiles: "Only Image Files",
    ImageMustSmallerThan5M: "Image Must Smaller 5MB",
    SelectAtLeastOneFriend: "Select At Least One Friend",
    NewConversation: "New Conversation",
    Create: "Create",
    ConversationName: "Conversation Name",
    OptionalGroupName: "Optinal Group Name",
    ConversationImage: "Conversation Image",
    ClickOrDragImageToUpload: "Click or Drag Image To Upload",
    SupportSingleImageUpload: "Support for a single image",
    SelectFriends: "Select Friends",
    NoFriendsFound: "No Friends Found",
    Remove: "Remove",
    EditConversation: "Edit Conversation",
    Update: "Update",
    ConversationNameRequired: "Conversation Name Required",
    GroupName: "Group Name",
    ConversationUpdated: "Conversation Updated",
    ConfirmLeaveConversation: "Confirm Leave Conversation",
    LeftConversation: "Left Conversation",
    AddMembers: "Add Members",
    NoFriendsToAdd: "No Friends To Add",
    SelectFriendsToAdd: "Select Friends To Add",
    Add: "Add",
    MembersAdded: "Members Added",
    CurrentMembers: "Current Members",
    NoMembersInConversation: "No Members In Conversation",
    ManageMembers: "Manage Members",
  },
  People: {
    FetchUsersFailed: "Failed to fetch users!",
    ErrorFetchingUsers: "Error fetching users!",
    NoFriendRequests: "No friend requests",
    ErrorFriendRequests: "Error fetching friend requests!",
    AcceptScuccess: "Accept friend request successfully!",
    AcceptFailed: "Accept friend request failed!",
    AcceptError: "Error accepting friend request!",
    DeclineSuccess: "Decline friend request successfully!",
    DeclineFailed: "Decline friend request failed!",
    DeclineError: "Error declining friend request!",
    FriendRequestSent: "Friend request sent!",
    FriendRequestSentSuccess: "Friend request sent successfully!",
    FriendRequestFailed: "Friend request failed!",
    FriendRequestError: "Error sending friend request!",
    FriendRequestCanceled: "Friend request canceled!",
    FriendRequestCancelFailed: "Friend request cancel failed!",
    FriendRequestSentFailed: "Friend request sent failed!",
    FriendRequestSentError: "Error sending friend request!",
    FriendRequestCanceledSuccess: "Friend request canceled successfully!",
    FriendRequestCanceledFailed: "Friend request cancel failed!",
    FriendRequestCanceledError: "Error canceling friend request!",
  },
};
