export const VnLocalizedStrings = {
  Public: {
    All: "Tất cả",
    Confirm: "Xác nhận",
    Cancel: "Hủy",
    Back: "Quay lại",
    Save: "Lưu",
    Close: "Đóng",
    Language: "Ngôn ngữ: Tiếng Việt",
    Post: "Bài Viết",
    Friend: "Bạn Bè",
    Username: "Tên người dùng",
    About: "Giới Thiệu",
    Today: "Hôm nay bạn thế nào?",
    Detail: "Chi tiết",
    EditProfile: "Chỉnh sửa trang cá nhân",
    ChangePassword: "Thay đổi mật khẩu",
    LogOut: "Đăng xuất",
    SetingProfile: "Cài đặt trang cá nhân",
    Mail: "Email",
    Phone: "Số điện thoại",
    Birthday: "Ngày sinh",
    Active: "Ngày tham gia",
    FriendFind: "Tìm bạn bè",
    FriendView: "Xem tất cả bạn bè",
    Conform: "Xác nhận",
    LogoutConfirm: "Bạn có chắc chắn muốn đăng xuất",
    More: "Xem thêm",
    AddFriend: "Kết bạn",
    UnFriend: "Hủy kết bạn",
    CancelFriendRequest: "Hủy lời mời",
    RefuseFriendRequest: "Từ chối",
    AcceptFriendRequest: "Chấp nhận",
    ReportFriend: "Báo Cáo",
    Block: "Chặn",
    Vietnamese: "Tiếng Việt",
    English: "Tiếng Anh",
    ErrorFetchingProfile: "Lỗi hiển thị thông tin",
    Biography: "Giới thiệu",
    UnknownUser: "Người dùng YourVibes",
    Public: "Công khai",
    Everyone: "Mọi người",
    Private: "Chỉ mình tôi",
    MinuteAgo: "phút trước",
    HourAgo: "giờ trước",
    DayAgo: "ngày trước",
    Action: "Hành động",
    CommonActions: "Nhập bình luận của bạn ...",
    Comment: "Bình luận",
    Reply: "Trả lời",
    ReportComment: "Báo cáo bình luận",
    Day: "Ngày",
    HideInfo: "đã ẩn thông tin cá nhân",
    FriendOnly: "chỉ bạn bè được xem",
    UserLikePost: " Danh sách người dùng thích bài viết",
    NoUserLikePost: "Bài viết chưa có lượt thích",
    ReplyClick: " Ấn vào đây và nhập câu trả lời của bạn nào !!!",
    CommentClick: " Ấn vào đây và viết bình luận của bạn nào !!!",
    LoginLoading: "Đang đăng nhập vui lòng đợi ...",
    Home: "Trang chủ",
    Settings: "Cài đặt",
    Profile: "Tài khoản",
    LoginStatus: "Vui lòng đăng nhập lại",
    Messages: "Tin Nhắn",
    LoadMore: "Tải thêm",
    Search: "Tìm kiếm",
    Error: "Lỗi",
    Yes: "Có",
    No: "Không",
    Delete: "Xóa",
    GenericError: "Đã xảy ra lỗi, vui lòng thử lại sau",
    Message: "Nhắn tin",
    Trending: "Xu hướng",
    People: "Mọi người",
    Discover: "Khám phá mọi người",
    Connect: "Kết nối với những người bạn mới và mở rộng mạng lưới của bạn",
    UserNotFound: "Không tìm thấy người dùng",
    ShowOnlyUnrequested: "Chỉ hiển thị những người chưa gửi lời mời",
    SearchUsers: "Tìm người dùng",
    ErrorLoading: "Lỗi tải dữ liệu",
    FriendRequests: "Lời mời kết bạn",
    NoFriendRequests: "Không có lời mời kết bạn",
    Accept: "Chấp nhận",
    Decline: "Từ chối",
    AllUsers: "Hãy mở rộng mạng lưới của bạn",
    Feed: "Bảng tin",
    Birtday: "Lời nhắc sinh nhật!",
    Dayof: "Ngày sinh nhật:",
    YearsOld: "Tuổi",
    NoBirthdays: "Không có ngày sinh nhật nào",
    ConfirmLogoutMessage: "Bạn có chắc chắn muốn đăng xuất?",
    ConfirmLogout: "Xác nhận đăng xuất",
  },
  Suggested: {
    SuggestedFriends: "Những người bạn có thể biết",
    Hide: "Ẩn",
    SeeMore: "Xem thêm",
    Why: "Tại sao tôi lại thấy những người bạn này?",
    Dont: "Tôi không muốn thấy những người bạn này",
    AddFriend: "Kết bạn",
    FriendRequestSent: "Đã gửi..",
    WhyExplanation: "Những gợi ý này dựa trên các yếu tố như:",
    WhyFactor1: "Bạn bè chung",
    WhyFactor2: "Sở thích tương đồng",
    WhyFactor3: "Hoạt động gần đây trên mạng xã hội",
    WhyConclusion:
      "Chúng tôi sử dụng thuật toán để tìm những người bạn có thể quen biết hoặc muốn kết nối!",
      NoMoreSuggestions: "Không có gợi ý nữa!",
  },
  Form: {
    Label: {
      Email: "Email",
      Password: "Mật khẩu",
      FamilyName: "Họ",
      Name: "Tên",
      Phone: "Số điện thoại",
      BirthDay: "Ngày sinh",
      GetOTP: "Nhập OTP",
      OTP: "Mã OTP",
      ConfirmPassword: "Xác nhận mật khẩu",
      Biography: "Tiểu sử",
    },
    RequiredMessages: {
      FamilyNameRequiredMessage: "Vui lòng nhập họ!",
      NameRequiredMessage: "Vui lòng nhập tên!",
      PhoneRequiredMessage: "Vui lòng nhập số điện thoại!",
      BirthDayRequiredMessage: "Vui lòng chọn ngày sinh!",
      EmailRequiredMessage: "Vui lòng nhập email!",
      PasswordRequiredMessage: "Vui lòng nhập mật khẩu!",
      ConfirmPasswordRequiredMessage: "Vui lòng xác nhận mật khẩu!",
      AgreeRequiredMessage: "Vui lòng đồng ý các điều khoản!",
      OTPRequiredMessage: "Vui lòng nhập mã OTP!",
      OTPPressRequiredMessage: "Vui lòng nhận mã OTP!",
      BirthDayInvalidMessage: "Ngày không phù hợp!",
      PhoneInvalidMessage: "Số điện thoại không phù hợp!",
      InvalidEmailMessage: "Email không hợp lệ!",
      PasswordMinLengthMessage: "Mật khẩu phải từ 8 kí tự!",
    },
    TypeMessage: {
      EmailTypeMessage: "Email không hợp lệ!",
      PasswordTypeMessage: "Mật khẩu phải trên 8 kí tự!",
      ConfirmPasswordTypeMessage: "Xác nhận mật khẩu không hợp lệ!",
      OTPTypeMessage: "Mã OTP phải là chuỗi 6 số!",
      PhoneTypeMessage: "Số điện thoại phải là chuỗi 10 số!",
      PleaseOldPasswordDifferentNewPassword:
        "Mật khẩu mới phải khác mật khẩu cũ!",
      PleaseInformationDifferent: "Vui lòng nhập đầy đủ thông tin",
    },
  },
  Login: {
    LoginButton: "Đăng nhập",
    ForgotPasswordText: "Quên mật khẩu?",
    DontHaveAccout: "Bạn chưa có tài khoản?",
    SignUpNow: "Đăng ký ngay!",
    Or: "Hoặc",
    LoginFailed: "Sai tài khoản hoặc mật khẩu!",
    AccountLocked: "Tài khoản của bạn đã bị khóa",
    changeLanguage: "Thay đổi ngôn ngữ sang: Tiếng Anh",
    InvalidInput: "Không hợp lệ",
    LoginSuccess: "Đăng nhập thành công!",
  },
  SignUp: {
    SignUpButton: "Đăng ký",
    SignUpSuccess: "Đăng ký thành công! Vui lòng đăng nhập lại",
    SignUpFailed: "Đăng ký thất bại!",
    OTPSuccess: "OTP đã được gửi thành công!",
    OTPAlreadySent: "Mã OTP đã được gửi và tồn tại trong 10 phút!",
    OTPFailed: "Gửi OTP thất bại!",
    OTPExpired: "Mã OTP không tồn tại hoặc đã hết hạn!",
    OTPFailedUserHasRegistered: "Tài khoản đã tồn tại!",
    OTPEmail: "OTP đã được gửi đến email của bạn",
    AlreadyHaveAccount: "Bạn đã có tài khoản?",
    LoginNow: "Đăng nhập ngay!",
    AgreePolicies: "Tôi đồng ý các điều khoản của YourVibes",
  },
  AddPost: {
    NewPost: "Bài đăng mới",
    WhatDoYouThink: "Bạn đang nghĩ gì?",
    PrivacyText: "Bài đăng được chia sẻ với",
    PostNow: "Đăng ngay",
    CreatePostSuccess: "Đăng bài thành công!",
    CreatePostFailed: "Đăng bài thất bại!",
    EmptyContent: "Thiếu nội dung hoặc file media",
    PickImgFailed: "Tải file thất bại!",
    UploadImage: "Tải hình ảnh",
    CensorPost: "Bài viết của bạn đang được kiểm duyệt, vui lòng chờ.",
  },
  ObjectPostPrivacy: {
    PublicDescription: "Bất kỳ ai ở trên YourVibes",
    FriendDescription: "Chỉ bạn bè của bạn ở trên YourVibes",
    PrivateDescription: "Chỉ bạn có thể nhìn thấy",
    PostPrivacy: "Quyền riêng tư của bài viết",
    Contents: {
      WhoCanSee: "Ai có thể nhìn thấy bài viết của bạn?",
      CanFind:
        "Bài viết của bạn có thể hiện thị trên trang cá nhân và trong kết quả tìm kiếm.",
      DefaultPrivacy1: "Tuy đối tượng mặc định là ",
      DefaultPrivacy2:
        ", nhưng bạn có thể thay đổi Quyền riêng tư của riêng bài viết này.",
    },
    ChoosePrivacy: "Chọn Đối tượng",
  },
  ObjectProfile: {
    ProfilePrivacy: "Quyền riêng tư của thông tin cá nhân",
    Contents: {
      WhoCanSee: "Ai có thể nhìn thấy thông tin của bạn?",
      DefaultPrivacy2:
        ", nhưng bạn có thể thay đổi quyền riêng tư cho thông tin tài khoản của mình.",
    },
  },
  Post: {
    EditPost: "Chỉnh sửa bài đăng",
    EditPrivacy: "Chỉnh sửa quyền riêng tư",
    DeletePost: "Xóa bài đăng",
    Advertisement: "Quảng cáo bài đăng",
    ReportPost: "Báo cáo bài đăng",
    LikePostFailed: "Thích bài viết thất bại!",
    SharePostSuccess: "Chia sẻ bài viết thành công!",
    SharePostFailed: "Chia sẻ bài viết thất bại!",
    SharePost: "Chia sẻ",
    DeleteNewFeed: "Ẩn bài viết",
    NoContent: "Nội dung không hiển thị",
    Sponsor: "Được tài trợ",
    NoPosts: "Không có bài viết nào",
    ShareContent: "Nhập nội dung chia sẻ của bạn...",
    CharacterLimit: "10000 ký tự",
    CharacterLimitR: "255 ký tự",
    NoTrendingPosts: "Chưa có bài viết trending nào",
  },
  PostDetails: {
    ViewReplies: "Xem phản hồi",
    HideReplies: "Ẩn phản hồi",
    Save: "Lưu",
    Cancel: "Hủy",
    Error: "Lỗi",
    ErrorReplies: "Lỗi phản hồi",
    ReportComment: "Báo cáo bình luận",
    EditComment: "Chỉnh sửa bình luận",
    DeleteComment: "Xóa bình luận",
    DeleteCommentSusesfully: "Xóa bình luận thành công!",
    DeleteCommentFailed: "Xóa bình luận thất bại!",
    ActionOptions: "Chọn hành động",
    ReportSusesfully: "Báo cáo bình luận thành cônng!",
    Success: "Thành công",
    EditCommentSuccess: "Cập nhật bình luận thành công!",
    EditCommentFailed: "Cập nhật bình luận thát bị!",
    EditReplySuccess: "Cập nhật phản hồi thành công!",
    EditReplyFailed: "Cập nhật phản hồi thát bại!",
    DeteleReplyFailed: "Xóa phản hồi thát bại!",
    DeteleReplySuccess: "Xóa phản hồi này thành công!",
    CommentSuccess: "Bình luận thành công!",
    CommentFailed: "Bình luận thát bại!",
    ReplySuccess: "phản hồi thành công!",
    ReplyFailed: "phản hồi thát bại!",
    Yes: "Xác nhận",
    No: "Không",
    CommentNotFound: "Không tìm thấy bình luận!",
    CommentLimit: "500 ký tự!",
  },
  Profile: {
    Posts: {
      GetPostsFailed: "Lấy danh sách bài viết thất bại!",
      GetOnePostFailed: "Lấy bài viết thất bại!",
    },
    Info: {
      GetInfoFailed: "Lấy thống tin người dùng thất bại!",
    },
    Friend: {
      SendYouARequest: "Đã gửi cho bạn một lời mời kết bạn!",
      SendARequest: "Đã gửi lời mời kết bạn!",
      SendRequestFailed: "Gửi lời mời kết bạn thất bại!",
      SendRequestSuccess: "Gửi lời mời kết bạn thành công!",
      FriendResponseFailed: "Phản hồi lời mời thất bại!",
      FriendResponseSuccess: "Phản hồi lời mời thành công!",
      CancelRequestFailed: "Hủy lời mời thất bại!",
      CancelRequestSuccess: "Hủy lời mời thành công!",
      UnfriendFailed: "Hủy kết bạn thất bại!",
      UnfriendSuccess: "Hủy kết bạn thành công!",
      UnfriendConfirm: "Bạn có muốn hủy kết bạn với người dùng này?",
    },
  },
  UpdatePost: {
    UpdatePostSuccess: "Cập nhật bài đăng thành công!",
    UpdatePostFailed: "Cập nhật bài đăng thất bại!",
  },
  DeletePost: {
    DeleteConfirm: "Bạn chắc chắn muốn xóa bài viết này?",
    DeleteSuccess: "Xóa bài viết thành công!",
    DeleteFailed: "Xóa bài viết thát bại!",
  },
  UpdateProfile: {
    UpdateProfile: "Cập nhật trang cá nhân",
    UpdateFailed: "Cập nhật trang cá nhân thất bại!",
    UpdateSuccess: "Cập nhật trang cá nhân thành công!",
  },
  Search: {
    Search: "Tim kiếm",
    SearchPlaceholder: "Bạn đang tìm gì...",
    SearchFailed: "Tìm kiếm thất bại!",
    NoUsers: "Không tìm thấy người dùng",
    TrySearch: "Hãy nhập từ khóa cần tìm",
  },
  Notification: {
    Notification: "Thông báo",
    NoNotification: "Không có thông báo",
    Items: {
      LikePost: "đã thích bài viết của bạn: ",
      SharePost: "đã chia sẻ bài viết của bạn: ",
      CommentPost: "đã bình luận về bài viết của bạn: ",
      Friend: "đã gửi lời mời kết bạn.",
      AcceptFriend: "đã chấp nhận lời mời kết bạn của bạn.",
      NewPost: "đã đăng một bài viết mới.",
      LikeComment: "đã thích bình luận của bạn: ",
      NewPostPersonal: "bài viết của bạn đăng thành công:",
      NewPostError: "bài viết của bạn bị lỗi",
      BlockCreatePost: "bài viết của bạn đã bị chặn",
      nsfw: "vì chứa nội dung nhạy cảm",
      political: "vì chứa nội dung chính trị không phù hợp",
      violence: "vì chứa nội dung bạo lực",
      DeactivatePostContent:"bài viết của bạn đã bị chặn vì vi phạm các điều khoản và điều kiện của chúng tôi. Nếu bạn nghĩ rằng đây là một sai lầm, vui lòng liên hệ với bộ phận hỗ trợ của chúng tôi để được xem xét lại.",
      ActivacePostContent:"bài viết của bạn đã được kích hoạt lại sau khi xem xét. Cảm ơn bạn đã kiên nhẫn chờ đợi.",
      DeactivateCommentContent:"bình luận của bạn đã bị chặn vì vi phạm các điều khoản và điều kiện của chúng tôi. Nếu bạn nghĩ rằng đây là một sai lầm, vui lòng liên hệ với bộ phận hỗ trợ của chúng tôi để được xem xét lại.",
      ActivaceCommentContent:"bình luận của bạn đã được kích hoạt lại sau khi xem xét. Cảm ơn bạn đã kiên nhẫn chờ đợi.",
    },
  },
  ListFriends: {
    ListFriends: "Danh sách bạn bè",
    Search: "Tim kiếm . . .",
    ViewProfile: "Xem trang cá nhân",
    Unfriend: "Hủy kết bạn ",
    Block: "Chặn ",
    Cancel: "Hủy",
  },

  Ads: {
    Ads: "Quảng cáo bài viết",
    TimeAndBudget: "Khoảng thời gian và Ngân sách",
    Minimum: "- Tối thiểu: {{price}}/1 ngày (Tối đa: 30 ngày)",
    DaysAds: "Số ngày quảng cáo:",
    TimeAds: "Thời gian quảng cáo: ",
    BudgetAds: "Ngân sách: ",
    PaymentMethod: "Phương thức thanh toán",
    AdvertisePostFailed: "Quảng cáo bài viết thất bại!",
    AdvertisePostSuccess: "Quảng cáo bài viết thành công!",
    ActiveCampaign: "Chiến dịch đang thực hiện",
    HideCampaign: "Ẩn lịch sử",
    ShowCampaign: "Xem lịch sử",
    Campaign: "Chiến dịch",
    End: "Kết thúc",
    RemainingTime: "Thời gian còn lại",
    Day: "Ngày",
    Grant: "Kinh phí",
    Status: "Trạng thái",
    PaymentSuccess: "Thanh toán thành công",
    PaymentFailed: "Thanh toán thất bại",
    NoCampaign: "Không có chiến dịch nào",
    AdvertisePostPending:
      "Quảng cáo đang chờ xử lý, vui lòng kiểm tra lại quá trình.",
    CampaignStatus: "Trạng thái chiến dịch",
    Click: "Tổng số lượt ấn vào",
    TotalReach: "Tổng số lượt người tiếp cận",
    TotalImpressions: "Tổng số lượt xem",
    AdsManagement: "Bài quảng cáo",
    SelectAds: "Chọn bài viết để quảng cáo",
    NoAdsFound: "Không tìm thấy bài viết quảng cáo nào",
    SearchAds: "Tìm kiếm bài viết quảng cáo",
    ExportAds: "Xuất báo cáo quảng cáo",
    StartDay: "Ngày bắt đầu",
    EndDay: "Ngày kết thúc",
    ViewDetails: "Xem chi tiết",
    Voucher: "Mã giảm giá",
    InvalidVoucher: "Mã giảm giá không hợp lệ",
    VoucherApplied: "Mã giảm giá đã được áp dụng",
    StatusActive: "Trạng thái hoạt động của chiến dịch",
    Pending: "Chờ xử lý",
    Active: "Đang hoạt động",
    Done: "Đã hoàn thành",
    Completed: "Hoàn thành",
    ErrorFetchingStatistics: "Không tìm thấy thống kê quảng cáo",
    ViewHistory: "Xem lịch sử",
    NoHistoryFound: "Không tìm thấy lịch sử quảng cáo",
    HistoryforPost: "Lịch sử quảng cáo cho bài viết",
    NoAdsHistory: "Không có lịch sử quảng cáo",
    Discount: "Giảm giá",
    LimitDay:
      "- Giới hạn 30 ngày vì phương thức thanh toán MOMO không hỗ trợ thanh toán vượt hơn 30 ngày!",
  },

  Report: {
    ReportPost: " Tại sao bạn báo cáo bài viết này?",
    ReportUser: "Tại sao bạn báo cáo người dùng này?",
    ReportComment: "Tại sao bạn báo cáo bình luận này?",
    ReportSuccess: "Báo cáo thành công!",
    ReportFailed: "Báo cáo thất bại!",
    ReportUserFailed:
      "Báo cáo thất bại, bạn đã báo cáo tài khoản này trước đó!",
    ReportPostFailed: "Báo cáo thất bại, bạn đã báo cáo bài viết này trước đó!",
    ReportCommentFailed:
      "Báo cáo thất bại, bạn đã báo cáo bình luận này trước đó!",
    Note: "Nếu bạn nhận thấy sự đe dọa hoặc ai đó dang gặp nguy hiểm, đừng chần chừ mà hãy tìm ngay sự giúp đỡ và báo cho dịch vụ khẩn cấp ở địa phương trước khi báo cáo với YourVibes.",
    placeholder: "Viết lý do báo cáo của bạn ở đây...",
    Report: "Báo cáo",
    ReportAlreadyExists: "Báo cáo đã tồn tại",
  },

  ChangePassword: {
    ChangePassword: "Thay đổi mật khẩu",
    ChangePasswordFailed:
      "Thay đổi mật khẩu thất bại, vui lòng kiểm tra lại mật khẩu!",
    ChangePasswordSuccess: "Thay đổi mật khẩu thành công!",
    OldPassword: "Mật khẩu cũ",
    NewPassword: "Mật khẩu mới",
    ConformPassword: "Xác nhận mật khẩu mới",
    Email: "Email",
    SendOTP: "Nhận OTP",
    OTP: "Mã OTP",
    ConformChangePassword: "Xác nhận thay đổi mật khẩu",
  },

  Messages: {
    SearchUser: "Nhập tên người mà bạn muốn liên hệ",
    FriendBar: "Bạn bè",
    CreateChatGroup: "Tạo nhóm chat",
    ChooseFriendToChat: "Chọn cuộc trò chuyện để chat",
    ChooseFriendToConnect: "Chọn cuộc trò chuyện để nhắn tin",
    NoMessages: "Chưa có tin nhắn nào",
    EnterMessage: "Nhập tin nhắn",
    FindFriendInModal: "Tìm kiếm bạn bè",
    Cancel: "Hủy bỏ",
    Confirm: "Xác nhận",
    UserProfile: "Thông tin người dùng",
    ProfilePage: "Trang cá nhân",
    Block: "Chặn",
    Reply: "Trả lời",
    ScrollToBottom: "Cuộn xuống dưới",
    Connecting: "Đang kết nối",
    Connected: "Đã kết nối",
    You: "Bạn",
    MessageTooLong: "Tin nhắn không được vượt quá 500 ký tự",
    GroupMinimumMembers: "Nhóm chat phải có ít nhất 3 thành viên",
    GroupCreationFailed: "Tạo nhóm chat thất bại",
    UserNotLoggedIn: "Vui lòng đăng nhập",
    GroupSelectionInfo: "Vui lòng chọn ít nhất 2 bạn bè để tạo nhóm chat",
    SelectedFriends: "Đã chọn",
    MinimumFriends: "Tối thiểu",
    Error: "Lỗi",
    OK: "OK",
    Friends: "Bạn bè",
    NoConversations: "Không có cuộc trò chuyện nào",
    FriendsTab: "Bạn bè",
    AllContactsTab: "Tất cả liên hệ",
    Conversations: "Trò chuyện",
    SelectedMembers: "Thành viên đã chọn",
    StartConversation: "Bắt đầu cuộc trò chuyện",
    SelectConversation: "Chọn cuộc trò chuyện",
    SelectConversationToChat: "Chọn cuộc trò chuyện để chat",
    TypeMessage: "Nhập tin nhắn",
    ErrorFetchingConversations: "Lỗi không lấy được cuộc trò chuyện",
    ConfirmDeleteMessage: "Xác nhận xóa tin nhắn này ?",
    ConfirmDeleteConversation: "Xác nhận xóa cuộc trò chuyện này ?",
    ConversationDeleted: "Cuộc trò chuyện đã bị xóa!",
    DeleteConversation: "Xóa cuộc trò chuyện",
    LeaveConversation: "Rời cuộc trò chuyện",
    ErrorFetchingFriends: "Lỗi khi tải danh sách bạn bè",
    OnlyImageFiles: "Chỉ chấp nhận tệp hình ảnh",
    ImageMustSmallerThan5M: "Hình ảnh phải nhỏ hơn 5MB",
    SelectAtLeastOneFriend: "Chọn ít nhất một người bạn",
    NewConversation: "Cuộc trò chuyện mới",
    Create: "Tạo",
    ConversationName: "Tên cuộc trò chuyện",
    OptionalGroupName: "Tên nhóm (tuỳ chọn)",
    ConversationImage: "Hình ảnh cuộc trò chuyện",
    ClickOrDragImageToUpload: "Nhấn hoặc kéo thả ảnh để tải lên",
    SupportSingleImageUpload: "Chỉ hỗ trợ tải lên một ảnh",
    SelectFriends: "Chọn bạn bè",
    NoFriendsFound: "Không tìm thấy bạn bè",
    Remove: "Xóa",
    EditConversation: "Chỉnh sửa cuộc trò chuyện",
    Update: "Cập nhật",
    ConversationNameRequired: "Tên cuộc trò chuyện là bắt buộc",
    GroupName: "Tên nhóm",
    ConversationUpdated: "Cuộc trò chuyện đã được cập nhật",
    ConfirmLeaveConversation: "Xác nhận rời khỏi cuộc trò chuyện",
    LeftConversation: "Rời cuộc trò chuyện",
    AddMembers: "Thêm thành viên",
    NoFriendsToAdd: "Không có bạn bè nào để thêm",
    SelectFriendsToAdd: "Chọn bạn bè để thêm",
    Add: "Thêm",
    MembersAdded: "Thêm thành viên thành công",
    CurrentMembers: "Thành viên hiện tại",
    NoMembersInConversation: "Không có thành viên nào trong cuộc trò chuyện",
    ManageMembers: "Quản lý thành viên",
  },
  People: {
    FetchUsersFailed: "Tải danh sách người dùng thất bại",
    ErrorFetchingUsers: "Lỗi khi tải danh sách người dùng",
    NoFriendRequests: "Không có lời mời kết bạn nào",
    ErrorFriendRequests: "Lỗi khi tải danh sách lời mời kết bạn",
    AcceptScuccess: "Chấp nhận lời mời thành công",
    AcceptFailed: "Chấp nhận lời mời thất bại",
    AcceptError: "Lỗi khi chấp nhận lời mời",
    DeclineSuccess: "Từ chối lời mời thành công",
    DeclineFailed: "Từ chối lời mời thất bại",
    DeclineError: "Lỗi khi từ chối lời mời",
    FriendRequestSent: "Đã gửi lời mời kết bạn",
    FriendRequestSentError: "Lỗi khi gửi lời mời kết bạn",
    FriendRequestSentSuccess: "Gửi lời mời kết bạn thành công",
    FriendRequestCanceled: "Đã hủy lời mời kết bạn",
    FriendRequestCanceledError: "Lỗi khi hủy lời mời kết bạn",
    FriendRequestCanceledSuccess: "Hủy lời mời kết bạn thành công",
    FriendRequestSentFailed: "Gửi lời mời kết bạn thất bại",
    FriendRequestCanceledFailed: "Hủy lời mời kết bạn thất bại",
  },
};
